##Numpy: Package for Multidimensional array

In [1]:
import numpy as np

In [3]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [4]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [8]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
np.arange(1,31,5)

array([ 1,  6, 11, 16, 21, 26])

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [16]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [17]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
np.ones((2,5),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [22]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [23]:
np.eye((10))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [27]:
np.random.rand(3,5)

array([[0.80199526, 0.72068006, 0.93308777, 0.94357479, 0.850246  ],
       [0.52329172, 0.28207084, 0.05270381, 0.42002282, 0.39706779],
       [0.17148009, 0.51003659, 0.99545591, 0.11500816, 0.64295971]])

In [25]:
arr= np.random.rand(2,4)
arr

array([[0.16644151, 0.65832131, 0.2165498 , 0.68712065],
       [0.13618456, 0.96365016, 0.5413208 , 0.03785219]])

In [28]:
np.random.randint(2,100)

32

In [29]:
np.random.randint(20,56,100)

array([38, 23, 21, 20, 21, 33, 54, 20, 22, 55, 40, 29, 40, 33, 54, 47, 27,
       44, 24, 26, 39, 34, 36, 45, 26, 36, 52, 27, 28, 42, 22, 38, 28, 37,
       20, 43, 26, 37, 54, 27, 39, 25, 48, 29, 26, 25, 21, 44, 44, 53, 20,
       22, 28, 31, 23, 22, 52, 55, 21, 45, 24, 48, 40, 42, 23, 50, 25, 28,
       53, 25, 40, 26, 34, 50, 45, 23, 52, 48, 38, 46, 40, 45, 44, 25, 20,
       24, 49, 46, 42, 47, 38, 43, 35, 29, 40, 33, 23, 43, 28, 55])

In [31]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [32]:
rand_array=np.random.randint(0,100,20)
rand_array

array([69, 19, 71, 74, 40, 53, 12, 44, 22, 78, 84, 53, 80, 59, 41, 57, 31,
       37, 62, 95])

In [33]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [34]:
sample_array.reshape(4,3)

ValueError: cannot reshape array of size 30 into shape (4,3)

In [35]:
rand_array.max()

95

In [36]:
rand_array.argmax()

19

In [38]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
a= np.random.rand(2,3)
a

array([[0.22979083, 0.80400603, 0.93149115],
       [0.99588997, 0.00205472, 0.92662012]])

In [41]:
a.T

array([[0.22979083, 0.99588997],
       [0.80400603, 0.00205472],
       [0.93149115, 0.92662012]])

In [55]:
sample_array= np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [57]:
sample_array[0]

10

In [45]:
sample_array[2:4]

array([12, 13])

In [59]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [62]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [63]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [64]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [65]:
subset_sample_array[:]=100
subset_sample_array

array([100, 100, 100, 100, 100, 100, 100])

Two dimensional

In [66]:
import numpy as np

In [67]:
sample_matrix=np.array([[5,43,3,34],[23,2,43,34],[2,324,34,4]])
sample_matrix

array([[  5,  43,   3,  34],
       [ 23,   2,  43,  34],
       [  2, 324,  34,   4]])

In [68]:
sample_matrix[1,2]

43

In [69]:
sample_matrix[2,:]

array([  2, 324,  34,   4])

In [70]:
sample_matrix[2]

array([  2, 324,  34,   4])

In [71]:
sample_matrix[:]

array([[  5,  43,   3,  34],
       [ 23,   2,  43,  34],
       [  2, 324,  34,   4]])